"""empty message

Revision ID: c81e937c9f41
Revises: 9c7c0a725505
Create Date: 2023-03-31 14:58:34.535552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81e937c9f41'
down_revision = '9c7c0a725505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('booking_service_itemid', sa.String(length=50), nullable=False),
    sa.Column('booking_service', sa.String(length=150), nullable=False),
    sa.Column('booking_datetime', sa.DateTime(), nullable=False),
    sa.Column('is_canceled', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    # ### end Alembic commands ###
